#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Aliases (PM)
#


alias p="mpc toggle"
alias n="mpc next"

alias res="mplayer http://radio.canstream.co.uk:8004/live.mp3"
alias nts="mplayer http://134.213.27.207:8000/listen.pls"
alias rad4="get_iplayer --stream --type=liveradio \"Radio 4 FM\" --player=\"mplayer -cache 256 -\" --modes=hlsaacstd"
alias rad3="get_iplayer --stream --type=liveradio \"Radio 3 FM\" --player=\"mplayer -cache 256 -\" --modes=hlsaacstd"

alias m="mplayer"

alias dream="ssh 'paumar52@william-livingston.dreamhost.com'"
alias youandme="ssh 'alibor4@coweta.dreamhost.com'"
alias helpdesk="ssh helpdesk@helpdesk.staronline.org.uk"

alias dual="xrandr --output VGA1 --primary --auto --mode 1920x1080 --output LVDS1 --auto --mode 1600x900 --left-of VGA1"
alias single="xrandr --output LVDS1 --auto --mode 1600x900 --output VGA1 --off"
